### ISSUE TITLE
'Can't find variable: `ga`' on Safari

### ISSUE THREAD

**Issue by LasaleFamine** [justinribeiro/ga-dnt-analytics#1]
Seems that Safari (and also iPhones) can't load the `ga` library.

Here is what I get: 
![alt text](http://image.ibb.co/dsKtT5/Screen_Shot_2017_04_09_at_11_38_20.png)

There is something I'm missing?

On Chrome everything works well.

**Comment by justinribeiro** [comment]
Humm, interesting. I'll have a look at it today and see what's cooking.

**Comment by LasaleFamine** [comment]
I think I've got something: the `attachedCallback` seems be never called both on Safari (also Tech Preview) and Firefox (didn't try with Edge).   
I thought about my `webcomponents` polyfill that initially was the `lite` one, but also with the `webcomponents.js` polyfill I have the same result.

What do you think?

UPDATE: 
Just found the problem.  
I re-built the component in Polymer 1.0 and initially I had the same problem. After I have added the `<template></template>` tag within my `<dom-module>`, the `attached()` callback was suddenly called. 
Maybe this can be solved for your native component in the same way. Hope it helps!
